server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ics?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
    database: 0
  profiles:
    active: dev

mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty

#showSql
logging:
  level:
    com.initboot.assistant.mapper: debug